// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PM.Persistence.Context;

#nullable disable

namespace PM.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("PM.Domain.DTOs.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("First Name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Full Name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Last Name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Path Image");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "03389193-950d-4480-b099-908ac04732bf",
                            Email = "john.doe@example.com",
                            EmailConfirmed = false,
                            FirstName = "John",
                            FullName = "John Doe",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            PathImage = "john.jpg",
                            Phone = "123456789",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "john_doe"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f150db86-ef12-406e-bee9-5c0eecad483f",
                            Email = "jane.smith@example.com",
                            EmailConfirmed = false,
                            FirstName = "Jane",
                            FullName = "Jane Smith",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            PathImage = "jane.jpg",
                            Phone = "987654321",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "jane_smith"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5a28b5d6-1fba-44b9-8691-122be765c467",
                            Email = "michael.j@example.com",
                            EmailConfirmed = false,
                            FirstName = "Michael",
                            FullName = "Michael Johnson",
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            PathImage = "michael.jpg",
                            Phone = "234567890",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "michael_j"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b6721080-2237-48b9-b75b-abc8b52300a7",
                            Email = "emily.d@example.com",
                            EmailConfirmed = false,
                            FirstName = "Emily",
                            FullName = "Emily Davis",
                            LastName = "Davis",
                            LockoutEnabled = false,
                            PathImage = "emily.jpg",
                            Phone = "345678901",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "emily_d"
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d65bfde0-6143-4ee2-a28a-6384238fc7b1",
                            Email = "chris.b@example.com",
                            EmailConfirmed = false,
                            FirstName = "Chris",
                            FullName = "Chris Brown",
                            LastName = "Brown",
                            LockoutEnabled = false,
                            PathImage = "chris.jpg",
                            Phone = "456789012",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "chris_b"
                        });
                });

            modelBuilder.Entity("PM.Domain.DTOs.MemberInTaskDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Member Id");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Task Id");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TaskId");

                    b.ToTable("Member In Task");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            MemberId = "1",
                            TaskId = "1"
                        },
                        new
                        {
                            Id = "2",
                            MemberId = "2",
                            TaskId = "2"
                        },
                        new
                        {
                            Id = "3",
                            MemberId = "3",
                            TaskId = "3"
                        },
                        new
                        {
                            Id = "4",
                            MemberId = "4",
                            TaskId = "4"
                        },
                        new
                        {
                            Id = "5",
                            MemberId = "5",
                            TaskId = "5"
                        });
                });

            modelBuilder.Entity("PM.Domain.DTOs.PlanDTOs", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Create At");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("End At");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Plan Name");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Start At");

                    b.HasKey("Id");

                    b.ToTable("Plan");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CreateAt = new DateTime(2024, 10, 22, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3589),
                            EndAt = new DateTime(2024, 11, 22, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3592),
                            PlanName = "Plan A",
                            StartAt = new DateTime(2024, 10, 23, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3590)
                        },
                        new
                        {
                            Id = "2",
                            CreateAt = new DateTime(2024, 10, 22, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3597),
                            EndAt = new DateTime(2024, 12, 22, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3598),
                            PlanName = "Plan B",
                            StartAt = new DateTime(2024, 10, 24, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3598)
                        },
                        new
                        {
                            Id = "3",
                            CreateAt = new DateTime(2024, 10, 22, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3600),
                            EndAt = new DateTime(2025, 1, 22, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3601),
                            PlanName = "Plan C",
                            StartAt = new DateTime(2024, 10, 25, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3600)
                        },
                        new
                        {
                            Id = "4",
                            CreateAt = new DateTime(2024, 10, 22, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3602),
                            EndAt = new DateTime(2025, 2, 22, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3603),
                            PlanName = "Plan D",
                            StartAt = new DateTime(2024, 10, 26, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3603)
                        },
                        new
                        {
                            Id = "5",
                            CreateAt = new DateTime(2024, 10, 22, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3605),
                            EndAt = new DateTime(2025, 3, 22, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3607),
                            PlanName = "Plan E",
                            StartAt = new DateTime(2024, 10, 27, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3605)
                        });
                });

            modelBuilder.Entity("PM.Domain.DTOs.PlanInProjectDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Plan Id");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Project Id");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Plan In Project");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            PlanId = "1",
                            ProjectId = "1"
                        },
                        new
                        {
                            Id = "2",
                            PlanId = "2",
                            ProjectId = "2"
                        },
                        new
                        {
                            Id = "3",
                            PlanId = "3",
                            ProjectId = "3"
                        },
                        new
                        {
                            Id = "4",
                            PlanId = "4",
                            ProjectId = "4"
                        },
                        new
                        {
                            Id = "5",
                            PlanId = "5",
                            ProjectId = "5"
                        });
                });

            modelBuilder.Entity("PM.Domain.DTOs.PositionWorkOfMemberDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Position Id");

                    b.Property<string>("PostitionInProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("User Id");

                    b.HasKey("Id");

                    b.HasIndex("PostitionInProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Position Work Of Member");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            PositionId = "1",
                            UserId = "1"
                        },
                        new
                        {
                            Id = "2",
                            PositionId = "2",
                            UserId = "2"
                        },
                        new
                        {
                            Id = "3",
                            PositionId = "3",
                            UserId = "3"
                        },
                        new
                        {
                            Id = "4",
                            PositionId = "4",
                            UserId = "4"
                        },
                        new
                        {
                            Id = "5",
                            PositionId = "5",
                            UserId = "5"
                        });
                });

            modelBuilder.Entity("PM.Domain.DTOs.PostitionInProjectDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PositionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Position Description");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Position Name");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Project Id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Position In Project");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            PositionDescription = "Project Manager",
                            PositionName = "Manager",
                            ProjectId = "1"
                        },
                        new
                        {
                            Id = "2",
                            PositionDescription = "Software Developer",
                            PositionName = "Developer",
                            ProjectId = "2"
                        },
                        new
                        {
                            Id = "3",
                            PositionDescription = "Software Tester",
                            PositionName = "Tester",
                            ProjectId = "3"
                        },
                        new
                        {
                            Id = "4",
                            PositionDescription = "UI/UX Designer",
                            PositionName = "Designer",
                            ProjectId = "4"
                        },
                        new
                        {
                            Id = "5",
                            PositionDescription = "DevOps Engineer",
                            PositionName = "DevOps",
                            ProjectId = "5"
                        });
                });

            modelBuilder.Entity("PM.Domain.DTOs.ProjectDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Create At");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("Is Deleted");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Project Description");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Project Name");

                    b.Property<string>("ProjectVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Project Version");

                    b.Property<string>("Projectstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Project Status");

                    b.HasKey("Id");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CreateAt = "10/22/2024 9:59:51 PM",
                            IsDeleted = false,
                            ProjectDescription = "First project description",
                            ProjectName = "Project Alpha",
                            ProjectVersion = "1.0",
                            Projectstatus = "In Progress"
                        },
                        new
                        {
                            Id = "2",
                            CreateAt = "10/22/2024 9:59:51 PM",
                            IsDeleted = false,
                            ProjectDescription = "Second project description",
                            ProjectName = "Project Beta",
                            ProjectVersion = "1.1",
                            Projectstatus = "Completed"
                        },
                        new
                        {
                            Id = "3",
                            CreateAt = "10/22/2024 9:59:51 PM",
                            IsDeleted = false,
                            ProjectDescription = "Third project description",
                            ProjectName = "Project Gamma",
                            ProjectVersion = "1.2",
                            Projectstatus = "On Hold"
                        },
                        new
                        {
                            Id = "4",
                            CreateAt = "10/22/2024 9:59:51 PM",
                            IsDeleted = false,
                            ProjectDescription = "Fourth project description",
                            ProjectName = "Project Delta",
                            ProjectVersion = "1.3",
                            Projectstatus = "Cancelled"
                        },
                        new
                        {
                            Id = "5",
                            CreateAt = "10/22/2024 9:59:51 PM",
                            IsDeleted = false,
                            ProjectDescription = "Fifth project description",
                            ProjectName = "Project Epsilon",
                            ProjectVersion = "2.0",
                            Projectstatus = "In Progress"
                        });
                });

            modelBuilder.Entity("PM.Domain.DTOs.RoleApplicationUserInProjectDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Project Id");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Role Id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RoleId");

                    b.ToTable("Role Application User In Project");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ProjectId = "1",
                            RoleId = "1"
                        },
                        new
                        {
                            Id = "2",
                            ProjectId = "2",
                            RoleId = "2"
                        },
                        new
                        {
                            Id = "3",
                            ProjectId = "3",
                            RoleId = "3"
                        },
                        new
                        {
                            Id = "4",
                            ProjectId = "4",
                            RoleId = "4"
                        },
                        new
                        {
                            Id = "5",
                            ProjectId = "5",
                            RoleId = "5"
                        });
                });

            modelBuilder.Entity("PM.Domain.DTOs.RoleInProjectDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Role Description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Role Name");

                    b.HasKey("Id");

                    b.ToTable("Role In Project");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            RoleDescription = "Administrator Role",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = "2",
                            RoleDescription = "Contributor Role",
                            RoleName = "Contributor"
                        },
                        new
                        {
                            Id = "3",
                            RoleDescription = "Viewer Role",
                            RoleName = "Viewer"
                        },
                        new
                        {
                            Id = "4",
                            RoleDescription = "Editor Role",
                            RoleName = "Editor"
                        },
                        new
                        {
                            Id = "5",
                            RoleDescription = "Owner Role",
                            RoleName = "Owner"
                        });
                });

            modelBuilder.Entity("PM.Domain.DTOs.TaskDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Create At");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("End At");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Start At");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Task Description");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Task Name");

                    b.Property<string>("TaskStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Task Status");

                    b.HasKey("Id");

                    b.ToTable("Task");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CreateAt = new DateTime(2024, 10, 22, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3542),
                            EndAt = new DateTime(2024, 10, 27, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3550),
                            StartAt = new DateTime(2024, 10, 23, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3543),
                            TaskDescription = "Task description for project 1",
                            TaskName = "Task 1",
                            TaskStatus = "Pending"
                        },
                        new
                        {
                            Id = "2",
                            CreateAt = new DateTime(2024, 10, 22, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3552),
                            EndAt = new DateTime(2024, 10, 28, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3553),
                            StartAt = new DateTime(2024, 10, 24, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3552),
                            TaskDescription = "Task description for project 2",
                            TaskName = "Task 2",
                            TaskStatus = "Completed"
                        },
                        new
                        {
                            Id = "3",
                            CreateAt = new DateTime(2024, 10, 22, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3554),
                            EndAt = new DateTime(2024, 10, 29, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3555),
                            StartAt = new DateTime(2024, 10, 25, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3555),
                            TaskDescription = "Task description for project 3",
                            TaskName = "Task 3",
                            TaskStatus = "In Progress"
                        },
                        new
                        {
                            Id = "4",
                            CreateAt = new DateTime(2024, 10, 22, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3557),
                            EndAt = new DateTime(2024, 10, 30, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3558),
                            StartAt = new DateTime(2024, 10, 26, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3557),
                            TaskDescription = "Task description for project 4",
                            TaskName = "Task 4",
                            TaskStatus = "On Hold"
                        },
                        new
                        {
                            Id = "5",
                            CreateAt = new DateTime(2024, 10, 22, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3559),
                            EndAt = new DateTime(2024, 10, 31, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3560),
                            StartAt = new DateTime(2024, 10, 27, 21, 59, 51, 879, DateTimeKind.Local).AddTicks(3559),
                            TaskDescription = "Task description for project 5",
                            TaskName = "Task 5",
                            TaskStatus = "Pending"
                        });
                });

            modelBuilder.Entity("PM.Domain.DTOs.TaskInPlanDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Plan Id");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Task Id");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("TaskId");

                    b.ToTable("Task In Plan");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            PlanId = "1",
                            TaskId = "1"
                        },
                        new
                        {
                            Id = "2",
                            PlanId = "2",
                            TaskId = "2"
                        },
                        new
                        {
                            Id = "3",
                            PlanId = "3",
                            TaskId = "3"
                        },
                        new
                        {
                            Id = "4",
                            PlanId = "4",
                            TaskId = "4"
                        },
                        new
                        {
                            Id = "5",
                            PlanId = "5",
                            TaskId = "5"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<string>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PM.Domain.DTOs.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PM.Domain.DTOs.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<string>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM.Domain.DTOs.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PM.Domain.DTOs.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PM.Domain.DTOs.MemberInTaskDTO", b =>
                {
                    b.HasOne("PM.Domain.DTOs.PositionWorkOfMemberDTO", "PositionWorkOfMember")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM.Domain.DTOs.TaskDTO", "TaskDTO")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PositionWorkOfMember");

                    b.Navigation("TaskDTO");
                });

            modelBuilder.Entity("PM.Domain.DTOs.PlanInProjectDTO", b =>
                {
                    b.HasOne("PM.Domain.DTOs.PlanDTOs", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM.Domain.DTOs.ProjectDTO", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PM.Domain.DTOs.PositionWorkOfMemberDTO", b =>
                {
                    b.HasOne("PM.Domain.DTOs.PostitionInProjectDTO", "PostitionInProject")
                        .WithMany()
                        .HasForeignKey("PostitionInProjectId");

                    b.HasOne("PM.Domain.DTOs.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostitionInProject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PM.Domain.DTOs.PostitionInProjectDTO", b =>
                {
                    b.HasOne("PM.Domain.DTOs.ProjectDTO", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PM.Domain.DTOs.RoleApplicationUserInProjectDTO", b =>
                {
                    b.HasOne("PM.Domain.DTOs.ProjectDTO", "ProjectDTO")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM.Domain.DTOs.RoleInProjectDTO", "RoleInProject")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectDTO");

                    b.Navigation("RoleInProject");
                });

            modelBuilder.Entity("PM.Domain.DTOs.TaskInPlanDTO", b =>
                {
                    b.HasOne("PM.Domain.DTOs.PlanDTOs", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM.Domain.DTOs.TaskDTO", "TaskDTO")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("TaskDTO");
                });
#pragma warning restore 612, 618
        }
    }
}
